services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Jaeger UI
      - "4318:4318" # OTLP HTTP

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  django:
    build: .
    container_name: django-aws-terminal-websocket
    command: sh -c "python manage.py migrate && uvicorn vmwebsocket.asgi:application --host 0.0.0.0 --port 8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ENABLE_OTEL=1
      - OTEL_SERVICE_NAME=django-aws-terminal-websocket
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318/v1/traces
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}
    ports:
      - "8888:8000" # <-- изменено: хост-порт 8888 -> контейнерный порт 8000
    depends_on:
      - jaeger
      - redis
    volumes:
      - .:/app
    working_dir: /app

  celery-worker:
    build: .
    command: celery -A vmwebsocket worker --loglevel=info
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ENABLE_OTEL=1
      - OTEL_SERVICE_NAME=django-aws-terminal-websocket
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318/v1/traces
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DJANGO_HOST=django
      - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}
    depends_on:
      - redis
      - django
    volumes:
      - .:/app
    working_dir: /app

  celery-beat:
    build: .
    command: celery -A vmwebsocket beat --loglevel=info
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ENABLE_OTEL=1
      - OTEL_SERVICE_NAME=django-aws-terminal-websocket
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318/v1/traces
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DJANGO_HOST=django
      - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}
    depends_on:
      - redis
      - django
    volumes:
      - .:/app
    working_dir: /app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - jaeger
    environment:
      # можно добавить переменные для подключения к Jaeger, если нужно
      - GF_INSTALL_PLUGINS=grafana-jaeger-datasource
